meta_product_name: "Jamile Radloff"
meta_title: "Jamile Radloff Portfolio"
meta_description: "Jamile Radloff - Junior Full Stack Web Developer"
meta_image: "JR.png" # should exist in `app/assets/images/`
twitter_account: "@mileradloff"
